// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMVOIIJ4lW8D71nq4ShlpQHPpVS_txCAs',
    appId: '1:344059355507:web:a3efb7a07a4c8579bfe506',
    messagingSenderId: '344059355507',
    projectId: 'the-roots-d5ad6',
    authDomain: 'the-roots-d5ad6.firebaseapp.com',
    databaseURL: 'https://the-roots-d5ad6-default-rtdb.firebaseio.com',
    storageBucket: 'the-roots-d5ad6.firebasestorage.app',
    measurementId: 'G-4DFPRHV05C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbD1zS-EG60gL2J7FZddq0oaNPMJq2BRU',
    appId: '1:344059355507:android:7c464427f8591e95bfe506',
    messagingSenderId: '344059355507',
    projectId: 'the-roots-d5ad6',
    databaseURL: 'https://the-roots-d5ad6-default-rtdb.firebaseio.com',
    storageBucket: 'the-roots-d5ad6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiC2RyP_0W0d7owsD2gIZChGGkO_fZsyk',
    appId: '1:344059355507:ios:f64532441c501547bfe506',
    messagingSenderId: '344059355507',
    projectId: 'the-roots-d5ad6',
    databaseURL: 'https://the-roots-d5ad6-default-rtdb.firebaseio.com',
    storageBucket: 'the-roots-d5ad6.firebasestorage.app',
    iosBundleId: 'com.example.groot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiC2RyP_0W0d7owsD2gIZChGGkO_fZsyk',
    appId: '1:344059355507:ios:f64532441c501547bfe506',
    messagingSenderId: '344059355507',
    projectId: 'the-roots-d5ad6',
    databaseURL: 'https://the-roots-d5ad6-default-rtdb.firebaseio.com',
    storageBucket: 'the-roots-d5ad6.firebasestorage.app',
    iosBundleId: 'com.example.groot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMVOIIJ4lW8D71nq4ShlpQHPpVS_txCAs',
    appId: '1:344059355507:web:84d1bac7c2d39718bfe506',
    messagingSenderId: '344059355507',
    projectId: 'the-roots-d5ad6',
    authDomain: 'the-roots-d5ad6.firebaseapp.com',
    databaseURL: 'https://the-roots-d5ad6-default-rtdb.firebaseio.com',
    storageBucket: 'the-roots-d5ad6.firebasestorage.app',
    measurementId: 'G-JKC87MXSS8',
  );
}
